node {

    withMaven(maven:'maven') {
        
        stage('Initialize'){
    
    def mavenHome  = tool 'maven'
    def docker = "docker"
   
   
     }

        stage('Checkout') {
            git url: 'https://github.com/piomin/sample-spring-microservices.git', credentialsId: 'github-piomin', branch: 'master'
        }

        stage('Build') {
            sh 'mvn clean install'

        }
        stage('Build image') {
        /* This builds the actual image; synonymous to
         * docker build on the command line */

        app = docker.build("account-service:1.0")
        }

     }
      
}

