node {

    withMaven(maven:'maven') {
        
        stage('Initialize'){
    
    def mavenHome  = tool 'maven'
   
    env.PATH = "${dockerHome}/bin:${mavenHome}/bin:${env.PATH}"
     }

        stage('Checkout') {
            git url: 'https://github.com/piomin/sample-spring-microservices.git', credentialsId: 'github-piomin', branch: 'master'
        }

        stage('Build') {
            sh 'mvn clean install'

        }

        stage('Image') {
            dir ('account-service') {
                docker.build.inside("--volume=/var/run/docker.sock:/var/run/docker.sock") {
   // The build here

             //   def app = docker.build "localhost:5000/account-service:${env.version}"
                app.push()
                }
            }
        }

        stage ('Run') {
            docker.image("localhost:5000/account-service:${env.version}").run('-p 2222:2222 -h account --name account --link discovery')
        }

        stage ('Final') {
            build job: 'customer-service-pipeline', wait: false
        }      

    }

}

